Repository mkdev-genie/mkdev-front, pull requests merged in 2020-10, with the labels that each got.

#1 [CHORE] Update gitignore
  .gitignore
Labels: good first issue

#2 [CHORE] Update readme
  README.md
Labels: good first issue

#3 [CHORE] Set React Env
  .gitignore
Labels: Chore

#5 [CHORE] Set eslint airbnb & Fix lint error
  .eslintrc.js
  package.json
  src/index.js
  yarn.lock
Labels: Chore

#12 Feature/button
  src/components/Button.js
  src/pages/Home.js
Labels: Feat, question

#13 [FEAT] Make pages/Home base
  package.json
  src/App.js
  src/components/Button.js
  src/imgs/tmp.png
  src/pages/Home.js
Labels: Feat

#15 [FIX] App.js eslint error
  src/App.js
Labels: Fix
