Repository mkdev-genie/mkdev-front, pull requests merged in 2020-11, with the labels that each got.

#17 [FEAT] Add components
  src/components/Button.js
  src/components/MainTitle.js
  src/components/RoundedText.js
  src/components/ShareButton.js
  src/components/SubTitle.js
  src/imgs/icon-facebook.svg
  src/imgs/icon-kakaotalk.svg
  src/imgs/icon-link.svg
  src/imgs/icon-twitter.svg
  src/imgs/tmp.png
  src/pages/Home.js
Labels: Feat, help wanted

#19 [FEAT] Set result page structure
  src/pages/Result.js
Labels: Feat

#20 [FEAT] Convert path to absolute & Add Theme provider
  .eslintrc.js
  craco.config.js
  jsconfig.json
  package-lock.json
  package.json
  src/App.js
  src/Theme.js
Labels: Chore, Feat
