Repository mkdev-genie/mkdev-front, pull requests merged in 2021-02, with the labels that each got.

#37 [FEAT] Post result
  src/App.js
  src/pages/Question.js
  src/pages/Result.js
Labels: Feat

#38 [FEAT] Update count UI & typos
  src/pages/Home.js
Labels: Feat

#39 [FIX] Localhost to base url
  package-lock.json
  src/pages/Home.js
  src/pages/Question.js
  src/pages/Result.js
Labels: Fix

#41 [FEAT] Add sns test
  public/index.html
  src/components/ShareButton.js
  src/pages/Home.js
Labels: Feat

#42 [FIX] Api url
  src/pages/Home.js
  src/pages/Question.js
  src/pages/Result.js
Labels: Fix

#43 [FIX] Kakaotalk share
  .env
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/components/ShareButton.js
  src/pages/Home.js
  yarn.lock
Labels: Fix

#45 Set env when build package
  .env
  .github/workflows/main.yml
  .gitignore
Labels: Chore

#47 [ADD] post location.state
  package.json
  src/pages/Question.js
  src/pages/Result.js
Labels: Feat

#49 Update css style
  src/App.js
  src/Theme.js
  src/assets/images/icon-github.png
  src/assets/images/icon-warning.png
  src/components/BodyText.js
  src/components/Button.js
  src/components/Footer.js
  src/components/ListItem.js
  src/components/MainTitle.js
  src/components/ShareButton.js
  src/components/SubTitle.js
  src/pages/Home.js
  src/pages/Question.js
  src/pages/Result.js
Labels: Feat

#52 [ADD] Share from result
  src/components/ShareButton.js
  src/pages/Result.js
Labels: Chore, Feat

#53 [FEAT] Add images and Update sns share content
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/img-thumbnail.jpg
  public/index.html
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/assets/images/img-main.png
  src/assets/images/img-result1.png
  src/assets/images/img-result10.png
  src/assets/images/img-result11.png
  src/assets/images/img-result12.png
  src/assets/images/img-result2.png
  src/assets/images/img-result3.png
  src/assets/images/img-result4.png
  src/assets/images/img-result5.png
  src/assets/images/img-result6.png
  src/assets/images/img-result7.png
  src/assets/images/img-result8.png
  src/assets/images/img-result9.png
  src/assets/images/tmp.png
  src/components/ShareButton.js
  src/pages/Home.js
  src/pages/Question.js
  src/pages/Result.js
Labels: Feat
